### ISSUE TITLE
Shader projects need updating to 4.3

### ISSUE THREAD

**Issue by SimonDarksideJ** [windowsgamessamples/UnityPorting#2]
Not really an issue since opening the projects does the automatic upgrade but would be good for consistency if all the projects in the repository use the same level of Unity version

**Comment by PeterRush** [comment]
I think this was also related to the gitignore file excluding .meta files etc, which was causing several issues. I have resaved from 4.3 using visible metafiles and force text, and added all the new .meta and .asset files to repository.

**Comment by SimonDarksideJ** [comment]
Just refreshed from source and the projects still prompt to be upgraded so guess something else is still being ignored maybe.
Still not a real issue since it upgrades cleanly.

Do think the sample have value since they show correct implementations of shaders and known workaround issues.
